In [1]:
import pandas as pd
import numpy as np
from random import sample
import os
from dateutil.parser import parse

df = pd.read_csv("C:\SemV\DAV\weatherHistory.csv", parse_dates=['Formatted Date'])
df

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
0,2006-04-01 00:00:00+02:00,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251.0,15.8263,0.0,1015.13,Partly cloudy throughout the day.
1,2006-04-01 01:00:00+02:00,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259.0,15.8263,0.0,1015.63,Partly cloudy throughout the day.
2,2006-04-01 02:00:00+02:00,Mostly Cloudy,rain,9.377778,9.377778,0.89,3.9284,204.0,14.9569,0.0,1015.94,Partly cloudy throughout the day.
3,2006-04-01 03:00:00+02:00,Partly Cloudy,rain,8.288889,5.944444,0.83,14.1036,269.0,15.8263,0.0,1016.41,Partly cloudy throughout the day.
4,2006-04-01 04:00:00+02:00,Mostly Cloudy,rain,8.755556,6.977778,0.83,11.0446,259.0,15.8263,0.0,1016.51,Partly cloudy throughout the day.
...,...,...,...,...,...,...,...,...,...,...,...,...
96448,2016-09-09 19:00:00+02:00,Partly Cloudy,rain,26.016667,26.016667,0.43,10.9963,31.0,16.1000,0.0,1014.36,Partly cloudy starting in the morning.
96449,2016-09-09 20:00:00+02:00,Partly Cloudy,rain,24.583333,24.583333,0.48,10.0947,20.0,15.5526,0.0,1015.16,Partly cloudy starting in the morning.
96450,2016-09-09 21:00:00+02:00,Partly Cloudy,rain,22.038889,22.038889,0.56,8.9838,30.0,16.1000,0.0,1015.66,Partly cloudy starting in the morning.
96451,2016-09-09 22:00:00+02:00,Partly Cloudy,rain,21.522222,21.522222,0.60,10.5294,20.0,16.1000,0.0,1015.95,Partly cloudy starting in the morning.
96452,2016-09-09 23:00:00+02:00,Partly Cloudy,rain,20.438889,20.438889,0.61,5.8765,39.0,15.5204,0.0,1016.16,Partly cloudy starting in the morning.

In [ ]:
#a
df[['Humidity']].groupby(df['Summary']).mean()

In [2]:
#b
df['Formatted Date'].isnull().sum()
data = df.copy()

random_indices = data['Formatted Date'].sample(1000).index
data.loc[random_indices,'Formatted Date'] = np.nan

data['Formatted Date'].isna().value_counts()
data.fillna(method = 'ffill').loc[random_indices, 'Formatted Date'].head(5)

C:\Users\mishr\AppData\Local\Temp\ipykernel_11024\2979346052.py:9: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data.fillna(method = 'ffill').loc[random_indices, 'Formatted Date'].head(5)

18571    2008-08-20 18:00:00+02:00
26539    2009-04-17 18:00:00+02:00
80433    2015-12-11 11:00:00+01:00
17791    2008-04-19 06:00:00+02:00
28760    2009-02-18 07:00:00+01:00
Name: Formatted Date, dtype: object

In [3]:
#c
temp = df.copy()
dummy_yearMonths = ['Jan 2005', 'Feb 2016', 'Mar 2017', 'Apr 2018', 'May 2019', 'June 2021']
temp_size = len(temp)
temp['Dummy_Date'] = [sample(dummy_yearMonths,1)[0]

for i in range(temp_size)]
temp

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary,Dummy_Date
0,2006-04-01 00:00:00+02:00,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251.0,15.8263,0.0,1015.13,Partly cloudy throughout the day.,Feb 2016
1,2006-04-01 01:00:00+02:00,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259.0,15.8263,0.0,1015.63,Partly cloudy throughout the day.,May 2019
2,2006-04-01 02:00:00+02:00,Mostly Cloudy,rain,9.377778,9.377778,0.89,3.9284,204.0,14.9569,0.0,1015.94,Partly cloudy throughout the day.,June 2021
3,2006-04-01 03:00:00+02:00,Partly Cloudy,rain,8.288889,5.944444,0.83,14.1036,269.0,15.8263,0.0,1016.41,Partly cloudy throughout the day.,Jan 2005
4,2006-04-01 04:00:00+02:00,Mostly Cloudy,rain,8.755556,6.977778,0.83,11.0446,259.0,15.8263,0.0,1016.51,Partly cloudy throughout the day.,Apr 2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...
96448,2016-09-09 19:00:00+02:00,Partly Cloudy,rain,26.016667,26.016667,0.43,10.9963,31.0,16.1000,0.0,1014.36,Partly cloudy starting in the morning.,June 2021
96449,2016-09-09 20:00:00+02:00,Partly Cloudy,rain,24.583333,24.583333,0.48,10.0947,20.0,15.5526,0.0,1015.16,Partly cloudy starting in the morning.,Jan 2005
96450,2016-09-09 21:00:00+02:00,Partly Cloudy,rain,22.038889,22.038889,0.56,8.9838,30.0,16.1000,0.0,1015.66,Partly cloudy starting in the morning.,June 2021
96451,2016-09-09 22:00:00+02:00,Partly Cloudy,rain,21.522222,21.522222,0.60,10.5294,20.0,16.1000,0.0,1015.95,Partly cloudy starting in the morning.,June 2021
96452,2016-09-09 23:00:00+02:00,Partly Cloudy,rain,20.438889,20.438889,0.61,5.8765,39.0,15.5204,0.0,1016.16,Partly cloudy starting in the morning.,Feb 2016

In [5]:
#d
temp['Dummy_Date'].map(lambda d: parse(d))

0       2016-02-09
1       2019-05-09
2       2021-06-09
3       2005-01-09
4       2018-04-09
           ...
96448   2021-06-09
96449   2005-01-09
96450   2021-06-09
96451   2021-06-09
96452   2016-02-09
Name: Dummy_Date, Length: 96453, dtype: datetime64[ns]

In [6]:
#e
temp['Dummy_Date'].map(lambda d: parse(d))

0       2016-02-09
1       2019-05-09
2       2021-06-09
3       2005-01-09
4       2018-04-09
           ...
96448   2021-06-09
96449   2005-01-09
96450   2021-06-09
96451   2021-06-09
96452   2016-02-09
Name: Dummy_Date, Length: 96453, dtype: datetime64[ns]